/**
 * migration-convergence.ts — pure, testable logic for the migration
 * convergence gate (scripts/check-migration-convergence.mjs).
 *
 * The script shells out to the real applier (--dry-run) for the on-disk file
 * set and reads the runbook; everything else is pure string/set math so the
 * CI gate itself can be regression-tested without a filesystem or network.
 * The `.mjs` script imports these from dist/ (compiled by `nest build`) — the
 * same pattern scripts/validate-migrations.mjs uses for MIGRATION_PROBES.
 */

/** Marker that opens the canonical manifest block in MIGRATION_RUNBOOK.md. */
export const MANIFEST_BEGIN = '<!-- BEGIN MIGRATION MANIFEST';

/** Marker that closes the canonical manifest block in MIGRATION_RUNBOOK.md. */
export const MANIFEST_END = '<!-- END MIGRATION MANIFEST -->';

/**
 * Banner header inside the runbook's combined paste block — the same format
 * validate-migrations.mjs buildPasteBlock emits:
 *   -- =====================================================================
 *   -- MIGRATION 0005 · 0005_organization.sql
 *   -- =====================================================================
 */
const BANNER_RE = /^-- MIGRATION\s+(\d{4})\s*·\s*([0-9A-Za-z_]+\.sql)\s*$/gm;

export interface CombinedBlockIssue {
  file: string;
  detail: string;
}

export interface CombinedBlockCheck {
  present: boolean;
  count: number;
  issues: CombinedBlockIssue[];
}

/**
 * Normalize one migration's SQL the same way validate-migrations.mjs does
 * when it emits the paste block (CR → stripped entirely, strip trailing
 * whitespace per line, drop leading/trailing blank lines) so a banner's
 * content and the on-disk file are byte-comparable. CR is pure whitespace in
 * SQL — stripping every \r (CRLF → LF, and a lone trailing CR a CRLF-written
 * runbook can leave before the closing fence) means harmless EOL artifacts
 * never masquerade as content drift, while real content changes still
 * mismatch.
 */
export function normalizeSql(sql: string): string {
  return sql
    .replace(/\r/g, '')
    .replace(/[ \t]+$/gm, '')
    .replace(/^\n+|\n+$/g, '');
}

/**
 * Parse the canonical migration manifest out of the runbook text (between the
 * BEGIN/END MIGRATION MANIFEST markers). Returns the file list in manifest
 * order, or null when the markers are absent/inverted.
 */
export function parseManifest(text: string): string[] | null {
  const start = text.indexOf(MANIFEST_BEGIN);
  const end = text.indexOf(MANIFEST_END);
  if (start === -1 || end === -1 || end <= start) return null;
  const block = text.slice(start + MANIFEST_BEGIN.length, end);
  const files: string[] = [];
  for (const line of block.split(/\r?\n/)) {
    const m = line.match(/^\|\s*\d+\s*\|\s*`(\d{4}_.*\.sql)`\s*\|$/);
    if (m) files.push(m[1]);
  }
  return files;
}

/**
 * Build the marker-delimited manifest block from a file list — the inverse of
 * parseManifest. `eol` matches the doc's existing line-ending convention so a
 * --fix regen never mixes EOLs.
 */
export function buildManifestBlock(files: string[], eol: string): string {
  const lines = [
    `${MANIFEST_BEGIN} — canonical file set + order; regenerated by \`node scripts/validate-migrations.mjs --runbook\` or \`node scripts/check-migration-convergence.mjs --fix\`; do not hand-edit between markers -->`,
    '| # | Migration file |',
    '| - | -------------- |',
  ];
  files.forEach((f, i) => lines.push(`| ${i + 1} | \`${f}\` |`));
  lines.push(MANIFEST_END);
  return lines.join(eol);
}

export interface FileSetDiff {
  /** On disk, not documented in the manifest. */
  missing: string[];
  /** Documented in the manifest, not on disk. */
  extra: string[];
  /** Same set but a different order (or a different set — caller decides). */
  orderDrift: boolean;
}

/**
 * Diff the on-disk file set against the manifest's documented set: files on
 * disk not in the manifest (missing), files in the manifest not on disk
 * (extra), and whether the full ordered lists differ (orderDrift).
 */
export function diffFileSets(diskFiles: string[], manifestFiles: string[]): FileSetDiff {
  const diskSet = new Set(diskFiles);
  const manifestSet = new Set(manifestFiles);
  return {
    missing: diskFiles.filter((f) => !manifestSet.has(f)),
    extra: manifestFiles.filter((f) => !diskSet.has(f)),
    orderDrift: JSON.stringify(diskFiles) !== JSON.stringify(manifestFiles),
  };
}

/**
 * Find the fenced ```sql block that contains the `-- MIGRATION` banners, then
 * verify every banner: (a) its nnnn number must match the filename prefix it
 * claims, and (b) the SQL under it must byte-match (normalized) the on-disk
 * file it names. `readFile` is injected so tests can stub the filesystem —
 * the script passes a real reader that resolves supabase/migrations/<file>.
 *
 * Returns null when the runbook has no `-- MIGRATION` banner at all (caller
 * treats that as "no combined block"), otherwise a check result with per-file
 * issues.
 */
export function checkCombinedBlock(
  text: string,
  readFile: (file: string) => string | null,
): CombinedBlockCheck | null {
  const bannerIndex = text.indexOf('-- MIGRATION');
  if (bannerIndex === -1) return null;

  // The block is the ```sql fence that contains the banners (the runbook
  // also has other fences — bash + a sample query).
  const fenceStart = text.lastIndexOf('```sql', bannerIndex);
  const contentStart = fenceStart === -1 ? -1 : text.indexOf('\n', fenceStart) + 1;
  const fenceEnd = text.indexOf('\n```', bannerIndex);
  if (contentStart === -1 || fenceEnd === -1 || fenceEnd <= contentStart) return null;
  const block = text.slice(contentStart, fenceEnd);

  const banners: Array<{ number: string; file: string; index: number; length: number }> = [];
  let match: RegExpExecArray | null;
  while ((match = BANNER_RE.exec(block)) !== null) {
    banners.push({
      number: match[1],
      file: match[2],
      index: match.index,
      length: match[0].length,
    });
  }

  if (banners.length === 0) {
    return {
      present: true,
      count: 0,
      issues: [{ file: '(combined block)', detail: 'no -- MIGRATION banners inside the fenced SQL block' }],
    };
  }

  const issues: CombinedBlockIssue[] = [];
  for (let i = 0; i < banners.length; i += 1) {
    const banner = banners[i];

    // (a) nnnn prefix must match the filename it claims.
    if (!banner.file.startsWith(`${banner.number}_`)) {
      issues.push({
        file: banner.file,
        detail: `banner number ${banner.number} does not match the filename prefix — banner says ${banner.number} · ${banner.file}`,
      });
    }

    // (b) The SQL under this banner must byte-match the on-disk file.
    const start = banner.index + banner.length;
    const end = i + 1 < banners.length ? banners[i + 1].index : block.length;
    let section = block.slice(start, end);
    // Strip the section's own leading separator (-- ====…, emitted right
    // after the banner) AND the next section's opener separator that ends up
    // at the tail of this slice, so only the migration's own SQL remains.
    section = section
      .replace(/^\s*--\s*={5,}.*(?:\r?\n|$)/, '')
      .replace(/\s*--\s*={5,}\s*$/, '');
    const sectionSql = normalizeSql(section);

    const diskSql = readFile(banner.file);
    if (diskSql === null) {
      issues.push({
        file: banner.file,
        detail: 'banner references a migration file that does not exist on disk',
      });
      continue;
    }
    if (sectionSql !== normalizeSql(diskSql)) {
      issues.push({
        file: banner.file,
        detail: `SQL under the banner does not match supabase/migrations/${banner.file} (content-level mislabel)`,
      });
    }
  }

  return { present: true, count: banners.length, issues };
}
